config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: "users#new"
  resources :users,except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy' 
  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page:10)
  end


  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own article"
        redirect_to @article
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
            <% if article.categories.any?%>
              <div class="mt-2">
              <%= render article.categories%>
              </div>
            <%end%>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container col-sm-10">
      <%= render "/shared/errors", obj: @article%>
</div>
<div class="container">
    <%= form_with(model: article, class: "shadow p-3 mb-3 bg-info rounder",local: true) do |form| %>
    <div class="row mb-3 justify-content-center">
      <%= form.label :title, style: "display: block", class: "col-2 col-form-label text-light" %>
      <div class="col-sm-10">
        <%= form.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
      </div>
    </div>
      <div class="row mb-3">
      <%= form.label :description, style: "display: block", class: "col-2 col-form-label text-light" %>
        <div class="col-sm-10">
        <%= form.text_area :description,rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
      </div>
    </div>
    <div>
      <div class="row mb-3">
        <%= form.label :category, style: "display: block", class: "col-2 col-form-label text-light" %>
        <div class="col-sm-10">
        <%= form.collection_select(:category_ids, Category.all, :id, :name, {prompt: "Make your selection from the list below (can be empty)"}, {multiple: true, size: 3, class: "form-select shadow rounded"}) %>
      </div>
    </div>

    <div class="text-center">
      <%= form.submit class: "btn btn-outline-light" %>
    </div>
    <% end %>
    <%= link_to "[ Back to articles listing ]", articles_path, class: "row justify-content-center text-info mb-3" %>
</div>

app/views/articles/edit.html.erb
  <h1 class='text-center' mt-4>Edit article</h1>
    <%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1 class='text-center' mt-4>Listing all articles</h1>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
<%= render 'article'%>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>

app/views/articles/new.html.erb
  <h1 class='text-center' mt-4>Create a new article</h1>
    <%= render "form", article: @article %>

app/views/articles/show.html.erb
<h2 class='text-center mt-4'><%= @article.title%></h2>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">  
          <div class="card-header fst-italic">
            by <%= @article.user.username if @article.user%>
            <%= link_to gravatar_for(@article.user), user_path(@article.user)%>
            <% if @article.categories.any?%>
              <div class="mt-2">
              <%= render @article.categories%>
              </div>
            <%end%>
          </div>
            <div class="card-body">
              <div class="card-text text-start"><%=simple_format(@article.description)%></div>
              <%if logged_in? && (@article.user == current_user || current_user.admin?)%>
                <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
                <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
              <%end%>
            </div>
            <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %>, edited <%= time_ago_in_words (@article.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
</div>