config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: "users#new"
  resources :users,except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy' 
  resources :categories, except: [:destroy]
end

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading"><%= pluralize(obj.errors.count, "error") %> prohibited this <%= obj.class.name.downcase%> from being saved:</h4>
        <ul>
            <% obj.errors.each do |error| %>
                <li><%= error.full_message %></li>
            <% end %>
        </ul>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

app/views/shared/_footer.html.erb
  <footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; <%= link_to "Mario Alberto Mora", "https://www.marioalbertomora.com", class: "text-white"%> </small>
    </div>
  </footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler navbar-dark bg-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        </li>
        <li class="nav-item">
          <%=link_to "Bloggers", users_path, class: "nav-link"%>
        </li>
        <%if logged_in?%>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Articles
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Create New Article", new_article_path, class: "dropdown-item"%>
              <%= link_to "View Articles", articles_path, class: "dropdown-item"%>
            </ul>
          </li>
        <%else%>
          <%=link_to "Articles", articles_path, class: "nav-link"%>
        <%end%>      
        <%if logged_in?%>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Create New Category", new_category_path, class: "dropdown-item"%>
              <%= link_to "View Categories", categories_path, class: "dropdown-item"%>
            </ul>
          </li>
        <%else%>
          <%=link_to "Categories", categories_path, class: "nav-link"%>
        <%end%>  
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             <%= "(Admin)" if current_user.admin?%> Profile [<%= current_user.username%>]
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "View your profile", user_path(current_user), class: "dropdown-item"%>
              <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item"%>
              <li><hr class="dropdown-divider"></li>
              <%= link_to "Delete your profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure?"}%>
            </ul>
          </li>
        <li>
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link"%>
        </li>
         <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link"%>
        </li>
        <%end%>          

      </ul>
    </div>
  </div>
</nav>