config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: "users#new"
  resources :users,except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy' 
  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: {minimum:3, maximum:25}
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_action :require_admin, except: [:index,:show]
    def new
        @category = Category.new
    end

    def create
            @category = Category.new(category_params)
            respond_to do |format|
            if @category.save
                format.html { redirect_to category_url(@category), notice: "Category successfully created" }
                format.json { render :show, status: :created, location: @category }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @category.errors, status: :unprocessable_entity }
            end
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
            respond_to do |format|
            if @category.update(category_params)
                format.html { redirect_to category_url(@category), notice: "Category name updated successfully" }
                format.json { render :show, status: :created, location: @category }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @category.errors, status: :unprocessable_entity }
            end
        end
    end
    
    
    

    def index
        @categories = Category.paginate(page: params[:page], per_page:5)
    end

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page:10)
    end 

    private

    def category_params
       params.require(:category).permit(:name) 
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins can perform this action"
            redirect_to categories_path
        end
    end

end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill bg-info text-dark me-1"%>

app/views/categories/_form.html.erb
    <div class="container col-sm-10">
      <%= render "/shared/errors", obj: @category%>
    </div>
<div class="container">
    <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounder",local: true) do |form| %>
    <div class="row mb-3 justify-content-center">
      <%= form.label :name, "Category name", style: "display: block", class: "col-2 col-form-label text-light" %>
      <div class="col-sm-10">
        <%= form.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
         </div>
    </div>
    <div class="text-center">
      <%= form.submit(@category.new_record? ? "Submit" : "Update category", class: "btn btn-outline-light") %>
    </div>
</div>
    <% end %>

    
     

app/views/categories/edit.html.erb
  <h1 class='text-center mt-4' >Edit category name</h1>

  <%= render 'form'%>

 <div class="mb-3 text-center">
        <%= link_to '[ Cancel and return to category ]', category_path(@category), class: "text-danger" %>
 </div>  
  

app/views/categories/index.html.erb
<h1 class='text-center mt-4' >Categories</h1>
<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
  </div>
<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
            <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>

             </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
    <%= will_paginate @categories, :container => false %>
  </div>
  

app/views/categories/new.html.erb
  <h1 class='text-center mt-4' >Create a new Category</h1>

  <%= render 'form'%>

 <div class="mb-3 text-center">
        <%= link_to '[ Cancel and return to categories listing ]', categories_path, class: "text-danger" %>
 </div>  

app/views/categories/show.html.erb
  <h1 class='text-center mt-4' >Category: <%= @category.name %></h1>  

<div class='text-center' mt-4>
  <%if logged_in? && current_user.admin?%>
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info"%>  
  <%end%>  
</div>

<div>
  <h3 class='text-center' mt-4>Articles</h3>  
</div>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

   <%= render 'articles/article' %>

   <div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>